### ISSUE TITLE
could you provide annotations for reimplementing the orig_cliff yaml config file

### ISSUE THREAD

**Issue by ssssholmes** [pixelite1201/BEDLAM#1]
Hi, thanks for your work! Could you provide the coco, mpii, h36m, and mpi_inf_3dhp annotations for reimplementing the orig_cliff yaml config file?

**Comment by ssssholmes** [comment]
By the way, there seem many corrupted images (downloaded from in https://bedlam.is.tue.mpg.de/):

```
'static-office-hair': 'data/training_labels/all_npz_12_training/20221022_3_250_batch01handhair_static_bigOffice_30fps.npz',
'zoom-suburbd-hair': 'data/training_labels/all_npz_12_training/20221024_10_100_batch01handhair_zoom_suburb_d_30fps.npz',
'static-gym-hair':'data/training_labels/all_npz_12_training/20221024_3_10_100_batch01handhair_static_highSchoolGym_30fps.npz',
```

it is appreciated if you could help me check it.

**Comment by pixelite1201** [comment]
> By the way, there seem many corrupted images in the following subsets (downloaded from https://bedlam.is.tue.mpg.de/):
> 
> ```
> 'static-office-hair': 'data/training_labels/all_npz_12_training/20221022_3_250_batch01handhair_static_bigOffice_30fps.npz',
> 'zoom-suburbd-hair': 'data/training_labels/all_npz_12_training/20221024_10_100_batch01handhair_zoom_suburb_d_30fps.npz',
> 'static-gym-hair':'data/training_labels/all_npz_12_training/20221024_3_10_100_batch01handhair_static_highSchoolGym_30fps.npz',
> ```
> 
> it is appreciated if you could help me check it.

Hello,

Could you please provide more details? What do you mean by corrupted images? Also, can you make sure that the files were properly unzipped?

**Comment by ssssholmes** [comment]
> > By the way, there seem many corrupted images in the following subsets (downloaded from https://bedlam.is.tue.mpg.de/):
> > ```
> > 'static-office-hair': 'data/training_labels/all_npz_12_training/20221022_3_250_batch01handhair_static_bigOffice_30fps.npz',
> > 'zoom-suburbd-hair': 'data/training_labels/all_npz_12_training/20221024_10_100_batch01handhair_zoom_suburb_d_30fps.npz',
> > 'static-gym-hair':'data/training_labels/all_npz_12_training/20221024_3_10_100_batch01handhair_static_highSchoolGym_30fps.npz',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it is appreciated if you could help me check it.
> 
> Hello,
> 
> Could you please provide more details? What do you mean by corrupted images? Also, can you make sure that the files were properly unzipped?

I download the `20221024_3-10_100_batch01handhair_static_highSchoolGym_30fps.tar`. `20221022_3_250_batch01handhair_static_bigOffice_30fps.tar` and `20221024_10_100_batch01handhair_zoom_suburb_d_30fps` and unzipped them use `tar xvf filename`, then I find many images are broken like:
![seq_000000_0008](https://github.com/pixelite1201/BEDLAM/assets/48430696/30da8bcb-a28e-4d12-9a0c-d9e75a535930)

**Comment by ssssholmes** [comment]
I don't find broken images in other subsets.

**Comment by pixelite1201** [comment]
Could you please provide few names of the images so that I can check them at my end?

**Comment by ssssholmes** [comment]
for example
```
20221024_10_100_batch01handhair_zoom_suburb_d_30fps/png/seq_000000/seq_000000_0000.png
20221024_10_100_batch01handhair_zoom_suburb_d_30fps/png/seq_000000/seq_000000_0001.png
20221024_10_100_batch01handhair_zoom_suburb_d_30fps/png/seq_000000/seq_000000_0002.png


20221024_10_100_batch01handhair_zoom_suburb_d_30fps/png/seq_000000/seq_000000_0005.png
20221024_10_100_batch01handhair_zoom_suburb_d_30fps/png/seq_000000/seq_000000_0010.png

20221024_3-10_100_batch01handhair_static_highSchoolGym_30fps/png/seq_000002/seq_000002_0000.png
20221024_3-10_100_batch01handhair_static_highSchoolGym_30fps/png/seq_000002/seq_000002_0012.png
```

**Comment by pixelite1201** [comment]
I just downloaded and checked at my end. There seems to be no corrupted files. It seems to be an issue of download. Could you please try downloading again?

**Comment by ssssholmes** [comment]
> 

Thanks for your help. I will try to download them again.

**Comment by pixelite1201** [comment]
> Hi, thanks for your work! Could you provide the coco, mpii, h36m, and mpi_inf_3dhp annotations for reimplementing the orig_cliff yaml config file?

The instructions are [here](https://github.com/pixelite1201/BEDLAM/blob/master/docs/training.md#training-cliff-model-with-real-images)

**Comment by ssssholmes** [comment]
Thanks for your work! @pixelite1201 The problem is resolved.
