### ISSUE TITLE
label for multiple humans

### ISSUE THREAD

**Issue by baeckgoo** [pixelite1201/BEDLAM#13]
Thank you for your great dataset.
I'm trying to render multiple humans in a single image.

I've downloaded ground-truth labels in the following link:
https://bedlam.is.tue.mpg.de/imagesgt.html

I'm testing it with the following files:
```
- sequence: 20221010_3_1000_batch01hand
- label: all_npz_12_training/20221010_3_1000_batch01hand_6fps.npy
```
As you said, the file is with respect to the crop of a single person.
The rendering result using the above label file is as follows:
![image](https://github.com/pixelite1201/BEDLAM/assets/61775524/d3b2928d-5b7f-4cb9-a8f5-99c721dc28f0)

How can I get other label files for other two persons? 
There are three persons.

I found three files with similar name. But, the files are not related each other.
- 20221010_3_1000_batch01hand_6fps.npz
- 20221017_3_1000_batch01hand_6fps.npz
- 20221018_3-8_250_batch01hand_6fps.npz

Thank you.

**Comment by pixelite1201** [comment]
Hello,
As I have already reply through the mail, information of all subjects are contained in the same .npz file distinguishable by center flag. Please checkout the details in https://github.com/pixelite1201/BEDLAM/tree/master/data_processing code.
