### ISSUE TITLE
Training on real images

### ISSUE THREAD

**Issue by zhangy76** [pixelite1201/BEDLAM#14]
Hi,

I have setup the environments and run the training code "python train_smpl.py --cfg configs/orig_cliff.yaml". But errors occur in finding the images in Human3.6M and MPI-INF-3DHP.   

May I ask how you save the Human3.6M and MPI-INF-3DHP video data to image data? Is that starting from 1 with writing step 5 (seems not...)?

Thanks,
Yufei

**Comment by pixelite1201** [comment]
Hello,
Could you tell me what error occurs? Also it is not very clear what you mean by `starting from 1 with writing step 5`.

**Comment by zhangy76** [comment]
Hi,

Thank you for the quick reply! The errors are failing to load the images from Human3.6M and MPI-INF-3DHP.
<img width="1538" alt="Screenshot 2023-07-16 at 2 30 26 PM" src="https://github.com/pixelite1201/BEDLAM/assets/60193243/fc0abe61-fda4-4e76-8c5f-96036fd6a94a">


After I downloaded the video data from the website, I will need to extract and image frames from it. For a video, I save the images every 5 frames following the sequence order.

Yufei

**Comment by pixelite1201** [comment]
Sorry for the delay in reply. We have extracted all images into a folder and used every 5th frame. Here is a screenshot of one of the h3.6m folder after extracting images. 
![h3 6m_screenshot](https://github.com/pixelite1201/BEDLAM/assets/26616807/81838464-0bd3-498d-b280-7bdb55922ae8)

**Comment by chojinie** [comment]
@pixelite1201 Hi, author.
I am trying to train the CLIFF on real image sets. And have a similar issue as  zhangy76's problem.

i fix H36m issue with 50FPS. But, i wanna know about mpi_inf_3dhp dataset, What is the frame rate (FPS) at which images should be extracted from the 3DHP dataset?

**Comment by ouusan** [comment]
@chojinie  @zhangy76  @pixelite1201  hello, have you solved this problem and how can we prepare the dataset?
