### ISSUE TITLE
About the motion paramters: SMPL to SMPLX

### ISSUE THREAD

**Issue by yyvhang** [pixelite1201/BEDLAM#17]
Hi, thanks for the great work. I have some questions about the motion parameters. As the paper introduced, the motion is from AMASS, which contains the SMPL parameters, and the body parameters of SMPL will be slightly different when directly applied to SMPLX, like the following fig:
<img width="1190" alt="image" src="https://github.com/pixelite1201/BEDLAM/assets/94104185/47893d38-c7b1-46a5-a8de-8a804e3b4908">

I want to know whether the dataset directly applies SMPL parameters to SMPLX or converts SMPL parameters to SMPLX parameters, hope to get your reply!

**Comment by pixelite1201** [comment]
AMASS is also available in SMPL-X format. Please check out https://amass.is.tue.mpg.de/download.php
