### ISSUE TITLE
About Masks.

### ISSUE THREAD

**Issue by 1020244018** [pixelite1201/BEDLAM#18]
Hello, thank you for the nice work.

Due to the 'gtkps' does not include visibility of joints, I attempted to use the masks of people to determine.
Unfortunately, I found that the order of people in the Label is different from the order of people in the mask images.
(I test on  the scene '20221013_3-10_500_batch01hand_static_highSchoolGym_6fps',  seq_000000.   the mask image 'seq_000000_0000_02_body.png' is not matched with the third people in label )

How can I determine the mask for each person in the labels?

**Comment by tpsmpi** [comment]
Last two digits of mask filename denote subject index. This corresponds to the sequence group `Body` local index in the `be_seq.csv` ground truth file.

Example: `seq_000000_0000_02_body.png` is subject index 2 which corresponds to `rp_bianca_posed_019_1056` for sequence 0 in `20221013_3-10_500_batch01hand_static_highSchoolGym`.

**Comment by 1020244018** [comment]
Thanks for you help. Now I understand that it can correspond masks and the people in labels by a person's identity information.
A small issue is that the training labels lack the identity information of the people, it seems that I must regenerate 6fps NPZ to obtain it, is there a more convenient method?

发件人：tpsmpi ***@***.***>
发送日期：2023-08-11 17:46:28
收件人：pixelite1201/BEDLAM ***@***.***>
抄送人：1020244018 ***@***.***>,Author ***@***.***>
主题：Re: [pixelite1201/BEDLAM] About Masks. (Issue #18)

Last two digits of mask filename denote subject index. This corresponds to the sequence group Body local index in the be_seq.csv ground truth file.
Example: seq_000000_0000_02_body.png is subject index 2 which corresponds to rp_bianca_posed_019_1056 for sequence 0 in 20221013_3-10_500_batch01hand_static_highSchoolGym.

**Comment by pixelite1201** [comment]
If you want to add extra information in npz, generating them by modifying the code is the only way.
