### ISSUE TITLE
Losses on SMPL(x) pose parameters

### ISSUE THREAD

**Issue by fabienbaradel** [pixelite1201/BEDLAM#2]
Hi,
First of all congrats for accepted paper to CVPR. Thanks a lot for sharing the code and the dataset. This will be very helpful for the research community working on this field.
As far as I understand you are releasing SMPL-X parameters for BEDLAM. You are also releasing the regressor for mapping the SMPL-X vertices to the SMPL vertices. It seems that you are using it when you are training HMR for Human Mesh Recovery for estimating SMPL params. But you are computing the losses on the [SMPL pose parameters](https://github.com/pixelite1201/BEDLAM/blob/c79a9c8ae1f931c13e4e5c0ca371a35f514c8dea/train/losses/losses.py#L92) between the ground-truth SMPL-X pose parameters and the predicted ones given by your model. When using multiple training sets (e.g. H36M, MPI-INF-3DHP) you only have SMPL pose parameters, so it is okay if there is "mismatch" between SMPL-X and SMPL pose params?
I hope that my question is clear enough,
Fabien

**Comment by fabienbaradel** [comment]
Thanks a lot for your answer, this is quite clear :)
Looking forward the release of SMPL parameters.

**Comment by fabienbaradel** [comment]
Just one more question, when do you plan to release the SMPL fits on BEDLAM?
Thanks,

**Comment by fabienbaradel** [comment]
Hi @pixelite1201 , sorry for pinging you again but are you going to release SMPL fits? As far as I know we are not able to download them on your project page at the moment.
Thanks for your help,

**Comment by pixelite1201** [comment]
SMPL fits are available on Download page now.
