### ISSUE TITLE
Minor bug in dataloader

### ISSUE THREAD

**Issue by twehrbein** [pixelite1201/BEDLAM#20]
Hey! 
I believe I found a small bug in the code. In the dataset files, you transform the images twice from BGR2RGB during training. Once when loading the images and the second time before applying augmentations (https://github.com/pixelite1201/BEDLAM/blob/master/train/dataset/dataset.py#L134). This results in the model being trained on BGR images, but evaluated on RGB images. After fixing this and retraining the BEDLAM-CLIFF model, the metrics on 3DPW improve for ~1mm w.r.t. the numbers reported in the paper.

**Comment by pixelite1201** [comment]
THanks a lot! It does seem that BGR2RGB is used twice. I will verify the results and update the code.

**Comment by pixelite1201** [comment]
Updated the code. Once again thanks for the information.
