### ISSUE TITLE
A minor bug on gt files and a problem about SMPL-format npz files.

### ISSUE THREAD

**Issue by 1020244018** [pixelite1201/BEDLAM#21]
1. Hello, I found a small problem when I run the command 'python df_full_body.py' to generate npz files.
The content of the gt file '20221013_3_250_batch01hand_static_bigOffice' is missing. eg: seq_000000_camera.csv

2.I want to generate identity information for the SMPL format npz file, and the current code generation is for SMPLX format. The lengths of the two are not the same. It seems that I can only match through the 'center'.  Would it be convenient for you to release the SMPL version of NPZ generated code.

**Comment by tpsmpi** [comment]
Issue 1: Thank you for reporting this issue. The related file on the download server is now fixed.
+ `20221013_3_250_batch01hand_static_bigOffice_gt.tar.gz` 
  + XXH128 checksum: `59820943b3f7534c1450038438f876a5`

See Changelog in related BEDLAM download section for details.

**Comment by pixelite1201** [comment]
Issue 2: We have added code to generate SMPL npz formatted files. Let us know if you face any issues.
