### ISSUE TITLE
the synthesized image data used for training lacks SMPL

### ISSUE THREAD

**Issue by TDIT-haha** [pixelite1201/BEDLAM#22]
First of all, thank you very much for your work. I want to use synthetic data for SMPL training, but I only see the gt file (*. npz) of SMPLx on the official website. I do not have any SMPL or gt files related to obtaining addresses in issue and readme. Can you provide this?

**Comment by pixelite1201** [comment]
Hello,
We have release the BEDLAM training data in both SMPL-X/SMPL format in the Download section of the website. Please check more carefully.
