### ISSUE TITLE
find correspondent smpl and smplx format annotation

### ISSUE THREAD

**Issue by YongtaoGe** [pixelite1201/BEDLAM#23]
Hi, there. Thanks for your great work. I find that both smplx and smpl format annotations have been released. However, I cannot match them for a particular synthesis person. ( the number of annotations in smpl and smplx format npz files are different.

**Comment by pixelite1201** [comment]
Hello,
Your question is not very clear. If you need helpful answer please provide more detail.

**Comment by YongtaoGe** [comment]
Hi,

Let me make it more clear with an example.
```
The smpl format annotation file ('20221010_3_1000_batch01hand_6fps.npz') has 5000 annotations,
while the smplx format annotation file  ('20221010_3_1000_batch01hand_6fps.npz') has 5100 annotations.
```
The question is that I want to find both smpl and smplx annotations for the same person on the same image.

**Comment by pixelite1201** [comment]
Thanks for making it more clear. There could be some difference in discarding frames with many joints occluded in the two version. 
But we have the data_processing code available [here](https://github.com/pixelite1201/BEDLAM/tree/master/data_processing) for both versions. You could generate your own npz files with particular requirements.
