### ISSUE TITLE
Rendered depth image metric

### ISSUE THREAD

**Issue by YuxuanSnow** [pixelite1201/BEDLAM#24]
Hi,

i have a question regarding the metric of the provided depth frames. I randomly load one `.ext` depth image, and found that the average depth value is 1.2e8. I wonder what is the unit of this value and if it's possible to convert to more common metric like meter?

Thanks!

**Comment by YuxuanSnow** [comment]
@pixelite1201 @tpsmpi Could you please give me an answer?

**Comment by tpsmpi** [comment]
https://github.com/PerceivingSystems/bedlam_render/issues/14
