### ISSUE TITLE
Pretrain model of ResNet50 on COCO

### ISSUE THREAD

**Issue by SonNguyen2510** [pixelite1201/BEDLAM#27]
Thank you author for your amazing paper!
I am trying to retrain HMR with ResNet50 backbone. I'm wonder is there any pretrain ResNet50 backbone with COCO dataset?
If yes, where can I find the pretrain model?
Thank you very much!

**Comment by pixelite1201** [comment]
You can find the pretrained models here: https://github.com/HRNet/HRNet-Human-Pose-Estimation/tree/master

**Comment by SonNguyen2510** [comment]
thank you for your answer!
