### ISSUE TITLE
Can you provide other evaluation result data in smpl format

### ISSUE THREAD

**Issue by jihg88** [pixelite1201/BEDLAM#33]
Thank you for your exciting work. I want to test the effect on AGORA, BEDLAM-test and other data sets, but it is too time-consuming to rerun on my device. Can you directly provide smpl prediction results like ssp_cliff_smpl?

**Comment by pixelite1201** [comment]
No, we cannot provide the smpl predictions for other datasets like AGORA, BEDLAM-test because we never generated them. Since SSP ground truth data is in SMPL format, we need to convert BEDLAM-CLIFF predictions to SMPL. But AGORA, BEDLAM-test is already in SMPL-X and can be directly evaluated.
