### ISSUE TITLE
Image crop settings

### ISSUE THREAD

**Issue by kevsak5** [pixelite1201/BEDLAM#34]
Hi there,

This is an awesome work. I'm wondering what kind of image crop settings did you use for training? I'm wondering if you used a tight bounding box or with some margin, if so what will that be? Thank you!

**Comment by pixelite1201** [comment]
Hello,
You can find the detail about the crop settings in the code: https://github.com/pixelite1201/BEDLAM/blob/master/train/dataset/dataset.py#L187
