### ISSUE TITLE
Bedlam test split Images

### ISSUE THREAD

**Issue by nikosvasilik** [pixelite1201/BEDLAM#38]
Hello,

Could you provide instructions to download the Bedlam testing images, so we could upload to bedlam leaderboard?
The provided scripts download only the training images and the test set is not accessible through the bedlam website.

Thank you for the great work!

**Comment by ttxskk** [comment]
> Hello,
> 
> Could you provide instructions to download the Bedlam testing images, so we could upload to bedlam leaderboard? The provided scripts download only the training images and the test set is not accessible through the bedlam website.
> 
> Thank you for the great work!

Hi @nikosvasilik,

I noticed you've closed this issue. Could you kindly provide guidance on how to appropriately partition the dataset into train, validation, and test sets? Thank you for your help.

**Comment by ttxskk** [comment]
I found these from [here](https://bedlam.is.tue.mpg.de/imagesgt.html).

**Comment by nikosvasilik** [comment]
> I found these from [here](https://bedlam.is.tue.mpg.de/imagesgt.html).

Yes. This is the correct way!
