### ISSUE TITLE
Questions about annotations in BEDLAM

### ISSUE THREAD

**Issue by caposerenity** [pixelite1201/BEDLAM#4]
Thank you for your high-quality work! We are using this dataset for retrieval research and need to identify the identity of each person in sequence. However, we have encountered some issues.
Firstly, we found that only the Training Images 27 (20221019_3-8_250_highbmihand_orbit_stadium_6fps.tar) contains the ground truth labels of sequence (be_seq.csv) after downloading the images and labels from the project website.
Secondly, we noticed that some images, such as many images in 20221011_1_250_batch01hand_closeup_suburb_a_6fps, are rotated by 90 degrees.

We are wondering how we can access the be_seq.csv labels of other training images and how we can determine the identity and position of the persons in each frame of the sequences given the sequence-level (body, x, y, z, Yaw, Pitch, Roll) labels in be_seq.csv. Additionally, we are curious about the release date of the other assets of BEDLAM.

**Comment by caposerenity** [comment]
any updates? @pixelite1201

**Comment by pixelite1201** [comment]
Hello,

Thanks for your interest. Please checkout the data_processing code [here](https://github.com/pixelite1201/BEDLAM/tree/master/data_processing). This will answer most of your queries. Note that for retrieval research you can modify the processing code and add the identity of each person in output files. 
Regarding other assets release, please checkout the project page.

**Comment by caposerenity** [comment]
Thank you @pixelite1201 for your reply! The data_processing codes hepls a lot for understanding of generated labels, but the following problems remains unsolved:
1. We note that the **be_seq.csv** file is absent in almost all the **6-fps** image folders, which is necessary for obtaining person identities. We know that it is contained in the 30-fps images, but re-downloading the 2.2T source files costs too much time. Could you please help upload an independent zip file containing all be_seq.csv files?
2. Moreover, the processed 6-fps labels for '20221019_3-8_250_highbmihand_orbit_stadium_6fps.tar' is missing in all_npz_12_training.zip.
3. We are wondering about the specific meaning of each name field in body/identity label in be_seq.csv? For instance, one of such label is _male_40_us_0306_0018_, what does _us_, _0306_, and _0018_ refer to?

**Comment by pixelite1201** [comment]
1. be_seq.csv is part of **gt** which you can download by providing flag -gt. You don't need to download the images (-png) for that.
2. The mentioned scene is part of validation and you can find it in all_npz_12_validation.zip
3.  Those are the subjects from CAESER dataset and follow their convention. Please check out CAESER dataset for details.

**Comment by caposerenity** [comment]
Thank you so much! The reply addressed all my questions

**Comment by mzemlyanikin** [comment]
Hello @pixelite1201,
thank you for the dataset!

I see that `be_seq.csv` files contain information about body in the `Body` column, skin tone description (`texture_body` in `Comment` column).
Can you describe what information is available about clothing?
There is `texture_clothing` or ` texture_clothing_overlay`, what is the difference between them?
Is there an information about clothing shape?
