### ISSUE TITLE
Link to ClothinSimulation broken in Downlaod section

### ISSUE THREAD

**Issue by patrickESM** [pixelite1201/BEDLAM#40]
Hello ,

on the webpage of BEDLAM in the Download section (https://bedlam.is.tue.mpg.de/download.html)

the Link for [Simulated clothing data](https://bedlam.is.tue.mpg.de/clothingsim.php) is broken. It gives a 404 nginx error.

Thank you for your help.

Greetings

**Comment by gfgb** [comment]
Hi, sorry about the inconvenience. The link should work now.

Best,
Giorgio

**Comment by patrickESM** [comment]
thank you very much @gfgb!
