### ISSUE TITLE
Wrong smpl mesh

### ISSUE THREAD

**Issue by baeckgoo** [pixelite1201/BEDLAM#49]
Thank you for your awesome work!

I found that a smpl mesh is wrong like this.
<img width="375" alt="image" src="https://github.com/pixelite1201/BEDLAM/assets/61775524/1dea900f-56b0-439a-9765-a29d8c0cc0d1">

The image file is '20221019_3-8_1000_highbmihand_static_suburb_d/png/seq_000557/seq_000557_0025.png'.
When I render all meshes in the scene, the mesh is also wrongly projected. 
<img width="411" alt="image" src="https://github.com/pixelite1201/BEDLAM/assets/61775524/c1bad610-65e9-4c86-844a-754b2728d06c">

How can I detect this kind of wrong mesh in all scenes?

**Comment by pixelite1201** [comment]
Hello,
I have not noticed any such issues with the ground truth meshes. Please provide minimal reproducible example to test.
