### ISSUE TITLE
keypoints(skelton)

### ISSUE THREAD

**Issue by p0mad** [pixelite1201/BEDLAM#9]
Hi,
i was wondering if it is possible to extract keypoints/skelton from your model?
is there any pretrainted model for the skelton/keypoint detections?

Thanks
best regards

**Comment by pixelite1201** [comment]
Hello,
The provided ground truth data (.npz) files contain the keypoint/skeleton information. Please refer to the code here for more details: https://github.com/pixelite1201/BEDLAM/tree/master/data_processing
